travis:
  secure:
    BINSTAR_TOKEN: Ajms6VJ+pjuVlRTiO+Fm3NjCgxZJ3xFSQDR9tt0BxoRvVqdH4F8/f+VaBSAu0TdlFh8rcajKO1amA6qs28i86+nPo8kR+77kad6TPndBHgdfpzDHvHJu3MCOHFZSaLEkyAO17GhNDvd5F9tuMt2lUWSkiwFT6LFv/rMhhHHAKzLu1RGak6hyHdP+1Ru86m7k1P6RxvrfffbfgJeVlwA+BY9VusySatCv/0YEe3yIr01TFZNx+yef8+mEIIY2q0rQbA+s2d/7FBymY9Np385bJlNCBGZnwK5m0Pz6Iu8kP4fMtqKYeBsuS+rhAXP8HREyTQrClWa2sajmL2XR+RnULhFBye/NA5cizepdK9yYMn901r7+Kyfp+AI3wGxO40C7vIIDN4HRoxzybAyCKxV7HMEKNQiV6Og2OkGh7SxVR9NhcB5zCx37n+k45eF4wHCJk+v6q1nKO3ZmMK6cU5OeANarmy8mkY2VdwwQYBwZkcFvKvE1dCCAFl05BWu8WIghXkbzrMF1NuzF4D5nqfRN1bnVHuYtbDVgUOzYzP1ch5kFOPQghI2uu6mVh/LKyLCWlJ45IM8Dpg1331D4y2P6vRQqxs50CCSOFFEMqsvP0gvniHG1qhbZpfOpcZNLLddZsT4+Qm1NhMViKGuSx+Z73M5k7zyqZKfy6nHBvWZpiIg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
